# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "web-hdsm"

  config.vm.network :private_network, ip: "172.16.0.0", netmask: "255.255.0.0"
  config.vm.network :public_network, ip: "10.99.0.0", netmask: "255.255.0.0"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder "web", "/var/www/html"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Web server"
    vb.memory = 3072
    vb.cpus = 2
  end
  
config.vm.provision "shell",
    inline: "sudo apt-get update -y"

  config.vm.provision "shell",
    inline: "sudo apt-get install -y apache2"
end
